[default.limits]
forms = "64 kB"
json = "1 MiB"
msgpack = "2 MiB"
"file/jpg" = "5 MiB"

[debug]
address = "127.0.0.1"
port = 8000
workers = 1
keep_alive = 0
log_level = "normal"

[release]
address = "0.0.0.0"
port = 8000
workers = 12
keep_alive = 4
log_level = "critical"